// This file is auto-generated by running:
// pnpm openapi
// after the backend is running at http://localhost:5000
//
// For now, define the paths we expect from the .NET backend.

export type paths = {
  "/api/auth/login": {
    post: {
      requestBody: {
        content: {
          "application/json": {
            email: string;
            password: string;
          };
        };
      };
      responses: {
        200: {
          content: {
            "application/json": {
              accessToken: string;
            };
          };
        };
        401: {
          content: {
            "application/json": {
              error: string;
            };
          };
        };
      };
    };
  };
  "/api/auth/refresh": {
    post: {
      responses: {
        200: {
          content: {
            "application/json": {
              accessToken: string;
            };
          };
        };
        401: {
          content: {
            "application/json": {
              error: string;
            };
          };
        };
      };
    };
  };
  "/api/auth/revoke": {
    post: {
      responses: {
        200: {
          content: {
            "application/json": {
              success: boolean;
            };
          };
        };
      };
    };
  };
  "/api/users/me": {
    get: {
      responses: {
        200: {
          content: {
            "application/json": {
              user: {
                id: string;
                email: string;
                roles: string[];
              };
            };
          };
        };
        401: {
          content: {
            "application/json": {
              error: string;
            };
          };
        };
      };
    };
  };
  "/api/content/page/{slug}": {
    get: {
      params: {
        path: {
          slug: string;
        };
      };
      responses: {
        200: {
          content: {
            "application/json": {
              id: string;
              slug: string;
              title: string;
              sections: Array<{
                id: string;
                sectionKey: string;
                fields: Record<string, {
                  fieldType: string;
                  value: string | null;
                }>;
              }>;
            };
          };
        };
        404: {
          content: {
            "application/json": {
              error: string;
            };
          };
        };
      };
    };
  };
  "/api/content/admin/page/{slug}": {
    get: {
      params: {
        path: {
          slug: string;
        };
      };
      responses: {
        200: {
          content: {
            "application/json": {
              id: string;
              slug: string;
              title: string;
              sections: Array<{
                id: string;
                sectionKey: string;
                fields: Array<{
                  id: string;
                  fieldKey: string;
                  fieldType: string;
                  label: string;
                  draftValue: string | null;
                }>;
              }>;
            };
          };
        };
        401: {
          content: {
            "application/json": {
              error: string;
            };
          };
        };
        404: {
          content: {
            "application/json": {
              error: string;
            };
          };
        };
      };
    };
  };
  "/api/content/admin/field/{fieldId}": {
    put: {
      params: {
        path: {
          fieldId: string;
        };
      };
      requestBody: {
        content: {
          "application/json": {
            draftValue: string | null;
          };
        };
      };
      responses: {
        200: {
          content: {
            "application/json": {
              success: boolean;
            };
          };
        };
        401: {
          content: {
            "application/json": {
              error: string;
            };
          };
        };
      };
    };
  };
  "/api/content/admin/page/{pageId}/publish": {
    post: {
      params: {
        path: {
          pageId: string;
        };
      };
      responses: {
        200: {
          content: {
            "application/json": {
              success: boolean;
            };
          };
        };
        401: {
          content: {
            "application/json": {
              error: string;
            };
          };
        };
      };
    };
  };
  "/api/news": {
    get: {
      params: {
        query?: {
          pageSize?: number;
          page?: number;
        };
      };
      responses: {
        200: {
          content: {
            "application/json": {
              items: Array<{
                id: string;
                slug: string;
                title: string;
                summary: string;
                heroImageUrl: string | null;
                publishedAt: string | null;
              }>;
            };
          };
        };
      };
    };
  };
  "/api/media": {
    get: {
      params: {
        query?: {
          pageSize?: number;
          page?: number;
        };
      };
      responses: {
        200: {
          content: {
            "application/json": {
              items: Array<{
                id: string;
                url: string;
                fileName: string;
                mimeType: string;
                createdAt: string;
              }>;
            };
          };
        };
      };
    };
    post: {
      requestBody: {
        content: {
          "multipart/form-data": {
            file: Blob;
          };
        };
      };
      responses: {
        201: {
          content: {
            "application/json": {
              id: string;
              url: string;
              fileName: string;
            };
          };
        };
        401: {
          content: {
            "application/json": {
              error: string;
            };
          };
        };
      };
    };
  };
};
