import "server-only";
import { promises as fs } from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import sharp from "sharp";
import { fileTypeFromBuffer } from "file-type";
import { prismaWriter, prisma } from "@/src/lib/db/prisma";

/**
 * Media service — upload pipeline + URL helpers.
 *
 * Public contract:
 *   - `uploadImage` validates magic bytes (NEVER trusts the upload
 *     `Content-Type`), rejects SVG, enforces `MAX_UPLOAD_BYTES`,
 *     re-encodes the original into webp + avif variants via `sharp`,
 *     writes everything under `${MEDIA_UPLOAD_DIR}/<guid>/`, and
 *     inserts a `MediaAsset` row + 3 `MediaVariant` rows in a single
 *     transaction.
 *   - `getMediaUrl` returns the public URL for a given storage key +
 *     variant. Dev: `/media/<storageKey>`. Prod: `${MEDIA_BASE_URL}/...`.
 *   - `deleteMedia` removes files from disk and soft-deletes the
 *     `MediaAsset` row.
 *
 * Security notes:
 *   - SVGs are rejected outright — they can carry scripts and bypass
 *     our XSS sanitisation at render time.
 *   - Magic-byte detection (`file-type`) overrides whatever
 *     Content-Type the upload claimed.
 *   - We rotate the image with sharp's auto-rotate so EXIF orientation
 *     does not lie about dimensions.
 *   - All variants are generated by sharp — never by trusting the
 *     upload's claimed format.
 */

const DEFAULT_MAX_BYTES = 10 * 1024 * 1024; // 10 MiB
const VARIANT_WIDTH = 1200; // px; matches the spec's marketing usage

// Formats we accept. Anything else is rejected.
const ALLOWED_MIME = new Set([
  "image/jpeg",
  "image/png",
  "image/webp",
  "image/avif",
  "image/gif",
]);

// We expose 3 derived formats per upload: webp + avif (modern) +
// jpeg fallback (covers ancient browsers / email clients).
const DERIVED_FORMATS = ["webp", "avif", "jpeg"] as const;
type DerivedFormat = (typeof DERIVED_FORMATS)[number];

// Mapping from Prisma enum → extension on disk.
const FORMAT_EXT: Record<DerivedFormat, "webp" | "avif" | "jpg"> = {
  webp: "webp",
  avif: "avif",
  jpeg: "jpg",
};

// Reverse map for getMediaUrl lookup of MIME types in the variant
// table; used to construct URLs when only a `storageKey` is known.
const FORMAT_TO_MIME: Record<DerivedFormat, string> = {
  webp: "image/webp",
  avif: "image/avif",
  jpeg: "image/jpeg",
};

// ---------------------------------------------------------------------------
// Public types
// ---------------------------------------------------------------------------

export type MediaVariantFormat = "original" | "webp" | "avif";

export interface MediaVariant {
  format: "webp" | "avif" | "jpeg";
  storageKey: string;            // e.g. "<guid>/photo.webp"
  width: number | null;
  height: number | null;
  sizeBytes: number;
  mimeType: string;
}

export interface MediaAssetRecord {
  id: string;
  storageKey: string;            // GUID stem, no extension
  mimeType: string;
  width: number;
  height: number;
  sizeBytes: number;
  altText: string;
  uploadedById: string;
  uploadedAt: Date;
  variants: MediaVariant[];
}

export interface UploadImageInput {
  buffer: ArrayBuffer | Buffer;
  /** HINT ONLY — magic-byte detection overrides this. */
  mimeType: string;
  altText: string;
  uploadedById: string;
  /** Optional original filename; not used in storage path. */
  originalName?: string;
}

export interface UploadImageOptions {
  /** Hard cap. Defaults to MAX_UPLOAD_BYTES env (10 MiB). */
  maxBytes?: number;
}

// ---------------------------------------------------------------------------
// Errors
// ---------------------------------------------------------------------------

/**
 * Discriminated error class so the upload route can return precise
 * HTTP status codes (e.g. 413 for `TOO_LARGE`, 415 for `UNSUPPORTED`).
 */
export type MediaUploadErrorCode =
  | "TOO_LARGE"
  | "EMPTY_ALT_TEXT"
  | "UNSUPPORTED_TYPE"
  | "MALFORMED_IMAGE"
  | "STORAGE_FAILED"
  | "DB_FAILED";

export class MediaUploadError extends Error {
  public readonly code: MediaUploadErrorCode;
  public readonly detail?: string;

  public constructor(code: MediaUploadErrorCode, message: string, detail?: string) {
    super(message);
    this.name = "MediaUploadError";
    this.code = code;
    this.detail = detail;
  }
}

// ---------------------------------------------------------------------------
// Configuration
// ---------------------------------------------------------------------------

function getMaxBytes(override?: number): number {
  if (override !== undefined) return override;
  const envVal = process.env.MAX_UPLOAD_BYTES;
  if (envVal) {
    const parsed = Number.parseInt(envVal, 10);
    if (Number.isFinite(parsed) && parsed > 0) return parsed;
  }
  return DEFAULT_MAX_BYTES;
}

function getUploadDir(): string {
  const fromEnv = process.env.MEDIA_UPLOAD_DIR;
  // Default to the dev convention. Use forward slashes on Windows too.
  // The `turbopackIgnore: true` hint tells the bundler this dynamic
  // path is resolved at runtime only, not bundled into the static
  // output.
  return fromEnv
    ? path.resolve(fromEnv)
    : path.resolve(/* turbopackIgnore: true */ process.cwd(), "public", "media");
}

// ---------------------------------------------------------------------------
// uploadImage — the security-focused pipeline
// ---------------------------------------------------------------------------

/**
 * Upload an image to the media library.
 *
 * Validation order (cheapest first):
 *   1. altText is non-empty (spec: REQUIRED on MediaAsset).
 *   2. buffer.length <= MAX_UPLOAD_BYTES.
 *   3. Magic-byte MIME detection (file-type) — NEVER trusts the
 *      caller's `mimeType` hint.
 *   4. Reject SVG (`image/svg+xml`) outright.
 *   5. Reject anything not in ALLOWED_MIME.
 *   6. sharp metadata → width/height (auto-rotate first).
 *   7. Generate webp + avif + jpeg variants at 1200px wide.
 *   8. Write files to disk under a fresh GUID.
 *   9. Insert MediaAsset + MediaVariant rows in a transaction.
 */
export async function uploadImage(
  input: UploadImageInput,
  options: UploadImageOptions = {},
): Promise<MediaAssetRecord> {
  const { buffer, altText, uploadedById, originalName } = input;
  const buf = toNodeBuffer(buffer);
  const maxBytes = getMaxBytes(options.maxBytes);

  // 1. altText check.
  if (!altText || altText.trim().length === 0) {
    throw new MediaUploadError(
      "EMPTY_ALT_TEXT",
      "altText is required (accessibility spec).",
    );
  }

  // 2. Size cap.
  if (buf.length > maxBytes) {
    throw new MediaUploadError(
      "TOO_LARGE",
      `Upload exceeds ${maxBytes} bytes (got ${buf.length}).`,
    );
  }

  // 3. Magic-byte MIME detection.
  const detected = await fileTypeFromBuffer(buf);
  if (!detected) {
    throw new MediaUploadError(
      "UNSUPPORTED_TYPE",
      "Could not detect file type from magic bytes.",
    );
  }

  // 4. SVG rejection (defence in depth — file-type v19 narrows the
  //    detected MIME union to exclude `image/svg+xml`, so by the time
  //    we get here we already know the buffer is not SVG. We keep the
  //    caller's Content-Type check too in case the library changes).
  if (input.mimeType === "image/svg+xml") {
    throw new MediaUploadError(
      "UNSUPPORTED_TYPE",
      "SVG uploads are not permitted (script execution risk).",
    );
  }

  // 5. Allowed-type whitelist.
  if (!ALLOWED_MIME.has(detected.mime)) {
    throw new MediaUploadError(
      "UNSUPPORTED_TYPE",
      `Unsupported image type: ${detected.mime}.`,
    );
  }

  // 6. Read dimensions via sharp (auto-rotate).
  let width: number;
  let height: number;
  try {
    const rotated = sharp(buf).rotate();
    const meta = await rotated.metadata();
    if (!meta.width || !meta.height) {
      throw new Error("metadata missing width/height");
    }
    width = meta.width;
    height = meta.height;
  } catch (err) {
    throw new MediaUploadError(
      "MALFORMED_IMAGE",
      "Failed to read image metadata.",
      err instanceof Error ? err.message : String(err),
    );
  }

  // 7. Generate variants.
  const variantBufs: Record<DerivedFormat, Buffer> = {} as Record<
    DerivedFormat,
    Buffer
  >;
  const variantSizes: Record<DerivedFormat, { width: number; height: number }> =
    {} as Record<DerivedFormat, { width: number; height: number }>;
  for (const fmt of DERIVED_FORMATS) {
    const result = await encodeVariant(buf, fmt);
    variantBufs[fmt] = result.buffer;
    variantSizes[fmt] = { width: result.width, height: result.height };
  }

  // 8. Write files to disk under a fresh GUID.
  const guid = crypto.randomUUID();
  const originalExt = extensionForMime(detected.mime);
  const dir = path.join(getUploadDir(), guid);

  try {
    await fs.mkdir(dir, { recursive: true });
    await fs.writeFile(
      path.join(dir, `original.${originalExt}`),
      buf,
    );
    for (const fmt of DERIVED_FORMATS) {
      const ext = FORMAT_EXT[fmt];
      await fs.writeFile(
        path.join(dir, `${fmt}-${VARIANT_WIDTH}.${ext}`),
        variantBufs[fmt],
      );
    }
  } catch (err) {
    throw new MediaUploadError(
      "STORAGE_FAILED",
      "Failed to write upload to disk.",
      err instanceof Error ? err.message : String(err),
    );
  }

  // 9. Insert DB rows in a transaction.
  const storageKey = `${guid}/original.${originalExt}`;
  let record: MediaAssetRecord;
  try {
    record = await prismaWriter.$transaction(async (tx) => {
      const asset = await tx.mediaAsset.create({
        data: {
          storageKey,
          mimeType: detected.mime,
          width,
          height,
          sizeBytes: buf.length,
          altText: altText.trim(),
          uploadedById,
        },
      });

      const variants: MediaVariant[] = [];
      for (const fmt of DERIVED_FORMATS) {
        const ext = FORMAT_EXT[fmt];
        const variant = await tx.mediaVariant.create({
          data: {
            mediaAssetId: asset.id,
            format: fmt.toUpperCase() as "WEBP" | "AVIF" | "JPEG",
            width: variantSizes[fmt].width,
            height: variantSizes[fmt].height,
            sizeBytes: variantBufs[fmt].length,
            storageKey: `${guid}/${fmt}-${VARIANT_WIDTH}.${ext}`,
          },
        });
        variants.push({
          format: fmt,
          storageKey: variant.storageKey,
          width: variant.width,
          height: variant.height,
          sizeBytes: variant.sizeBytes,
          mimeType: FORMAT_TO_MIME[fmt],
        });
      }

      return {
        id: asset.id,
        storageKey: asset.storageKey,
        mimeType: asset.mimeType,
        width: asset.width,
        height: asset.height,
        sizeBytes: asset.sizeBytes,
        altText: asset.altText,
        uploadedById: asset.uploadedById,
        uploadedAt: asset.createdAt,
        variants,
      };
    });

    await prismaWriter.auditLog.create({
      data: {
        userId: uploadedById,
        action: "MEDIA_UPLOAD",
        entityType: "MediaAsset",
        entityId: record.id,
        before: null,
        after: JSON.stringify({
          storageKey: record.storageKey,
          mimeType: record.mimeType,
          sizeBytes: record.sizeBytes,
          altText: record.altText,
          originalName: originalName ?? null,
        }),
      },
    });
  } catch (err) {
    // Best-effort cleanup of files if the DB write fails.
    await safeUnlink(dir);
    throw new MediaUploadError(
      "DB_FAILED",
      "Failed to persist media asset.",
      err instanceof Error ? err.message : String(err),
    );
  }

  return record;
}

// ---------------------------------------------------------------------------
// getMediaUrl — URL helper used by `next/image` loader
// ---------------------------------------------------------------------------

/**
 * Returns the public URL for a given `storageKey` and variant.
 *
 * Default `MEDIA_BASE_URL` is empty → same-origin `/media/<storageKey>`.
 * In production set `MEDIA_BASE_URL=https://media.example.com` to point
 * at the IIS static vdir.
 *
 * Passing `variant: "webp"` or `"avif"` does NOT rewrite the path;
 * the caller is expected to pass the variant's storageKey directly
 * (see `MediaVariant.storageKey`).
 */
export function getMediaUrl(
  storageKey: string,
  variant: MediaVariantFormat = "original",
): string {
  const base = (process.env.MEDIA_BASE_URL ?? "").replace(/\/$/, "");
  const key = storageKey.replace(/^\//, "");
  if (variant === "original") {
    return `${base}/media/${key}`;
  }
  return `${base}/media/${key}`;
}

// ---------------------------------------------------------------------------
// deleteMedia
// ---------------------------------------------------------------------------

/**
 * Hard-deletes a MediaAsset from disk + soft-deletes the DB row
 * (`deletedAt` is not in our minimal schema, so we hard-delete the
 * DB row + remove the files).
 *
 * Authorisation is delegated to the caller — the route handler MUST
 * check `requireRole(["ADMIN"])` or "owner == actor" before invoking.
 */
export async function deleteMedia(id: string, actorId: string): Promise<void> {
  const asset = await prismaWriter.mediaAsset.findUnique({
    where: { id },
    include: { variants: true },
  });
  if (!asset) {
    throw new Error(`MediaAsset not found: ${id}`);
  }

  // Remove files from disk.
  const dir = path.dirname(path.join(getUploadDir(), asset.storageKey));
  await safeUnlink(dir);

  // Remove DB rows.
  await prismaWriter.$transaction([
    prismaWriter.mediaVariant.deleteMany({ where: { mediaAssetId: id } }),
    prismaWriter.mediaAsset.delete({ where: { id } }),
    prismaWriter.auditLog.create({
      data: {
        userId: actorId,
        action: "MEDIA_DELETE",
        entityType: "MediaAsset",
        entityId: id,
        before: JSON.stringify({ storageKey: asset.storageKey }),
        after: null,
      },
    }),
  ]);
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Convert an `ArrayBuffer` (web API) to a Node `Buffer`.
 */
function toNodeBuffer(input: ArrayBuffer | Buffer): Buffer {
  if (Buffer.isBuffer(input)) return input;
  return Buffer.from(new Uint8Array(input));
}

/**
 * Encode one derived format at a fixed width using sharp. Returns the
 * encoded buffer + the (width, height) after auto-rotate.
 */
async function encodeVariant(
  source: Buffer,
  format: DerivedFormat,
): Promise<{ buffer: Buffer; width: number; height: number }> {
  const pipeline = sharp(source).rotate().resize({
    width: VARIANT_WIDTH,
    withoutEnlargement: true,
    fit: "inside",
  });
  let buf: Buffer;
  switch (format) {
    case "webp":
      buf = await pipeline.webp({ quality: 82 }).toBuffer();
      break;
    case "avif":
      buf = await pipeline.avif({ quality: 55 }).toBuffer();
      break;
    case "jpeg":
      buf = await pipeline.jpeg({ quality: 82, mozjpeg: true }).toBuffer();
      break;
  }
  const meta = await sharp(buf).metadata();
  return {
    buffer: buf,
    width: meta.width ?? VARIANT_WIDTH,
    height: meta.height ?? VARIANT_WIDTH,
  };
}

function extensionForMime(mime: string): string {
  switch (mime) {
    case "image/jpeg":
      return "jpg";
    case "image/png":
      return "png";
    case "image/webp":
      return "webp";
    case "image/avif":
      return "avif";
    case "image/gif":
      return "gif";
    default:
      // Should be unreachable thanks to ALLOWED_MIME check, but fall
      // back to a safe extension.
      return "bin";
  }
}

async function safeUnlink(target: string): Promise<void> {
  try {
    await fs.rm(target, { recursive: true, force: true });
  } catch (err) {
    // Non-fatal: log but don't throw — DB cleanup is the priority.
    console.warn(
      `[media] failed to remove ${target}: ${
        err instanceof Error ? err.message : String(err)
      }`,
    );
  }
}

// ---------------------------------------------------------------------------
// Internal: list helper used by the media library UI
// ---------------------------------------------------------------------------

export interface ListMediaOptions {
  limit?: number;
  cursor?: string;
}

export async function listMedia(
  options: ListMediaOptions = {},
): Promise<MediaAssetRecord[]> {
  const rows = await prisma.mediaAsset.findMany({
    include: { variants: true },
    orderBy: { createdAt: "desc" },
    take: options.limit ?? 50,
  });
  return rows.map(toRecord);
}

function toRecord(row: {
  id: string;
  storageKey: string;
  mimeType: string;
  width: number;
  height: number;
  sizeBytes: number;
  altText: string;
  uploadedById: string;
  createdAt: Date;
  variants: Array<{
    format: string;
    storageKey: string;
    width: number | null;
    height: number | null;
    sizeBytes: number;
  }>;
}): MediaAssetRecord {
  return {
    id: row.id,
    storageKey: row.storageKey,
    mimeType: row.mimeType,
    width: row.width,
    height: row.height,
    sizeBytes: row.sizeBytes,
    altText: row.altText,
    uploadedById: row.uploadedById,
    uploadedAt: row.createdAt,
    variants: row.variants.map((v) => ({
      format: v.format.toLowerCase() as "webp" | "avif" | "jpeg",
      storageKey: v.storageKey,
      width: v.width,
      height: v.height,
      sizeBytes: v.sizeBytes,
      mimeType: FORMAT_TO_MIME[v.format.toLowerCase() as DerivedFormat],
    })),
  };
}